# Generated by Django 6.0.6 on 2026-07-06 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'ඇණවුම', 'verbose_name_plural': 'ඇණවුම් (Orders)'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'ඇණවුම් අයිතමය', 'verbose_name_plural': 'ඇණවුම් කරන ලද චොකලට්'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at', 'name'], 'verbose_name': 'භාණ්ඩය', 'verbose_name_plural': 'චොකලට් / භාණ්ඩ'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ලැබුණු මුදල (රු.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ඉතිරි මුදල (රු.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='දිනය සහ වේලාව'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='ඕඩර් අංකය'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='මුළු මුදල (රු.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='මුළු පිරිවැය (රු.)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ඇතුළත් කළ දිනය'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_core.order', verbose_name='ඇණවුම'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_core.product', verbose_name='චොකලට් වර්ගය'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ප්\u200dරමාණය'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ඒකක පිරිවැය'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ඒකක මිල'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='බාර්කෝඩ් එක (Barcode)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ගත් මිල (රු.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ඇතුළත් කළ දිනය'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='ඡායාරූපය'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ක්\u200dරියාකාරී තත්ත්වය'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='චොකලට් නම'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='විකුණුම් මිල (රු.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='තොග ප්\u200dරමාණය'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='යාවත්කාලීන කළ දිනය'),
        ),
    ]
