# Generated by Django 6.0.6 on 2026-07-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_core', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='අතින් ඇතුළත් කළ නම'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_core.product', verbose_name='චොකලට් වර්ගය'),
        ),
    ]
